// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8lwaxbRvS6XIqeyNqhXq7XnI9RmAPLY',
    appId: '1:489498507185:web:7e10a6bb941127e8b66f90',
    messagingSenderId: '489498507185',
    projectId: 'pharmgo-bd4c6',
    authDomain: 'pharmgo-bd4c6.firebaseapp.com',
    storageBucket: 'pharmgo-bd4c6.appspot.com',
    measurementId: 'G-VRPHV85X1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAieoC62t5m9I2ylJ6nH7AHSMkSHZfDcuM',
    appId: '1:489498507185:android:2f53f31dc86f89b3b66f90',
    messagingSenderId: '489498507185',
    projectId: 'pharmgo-bd4c6',
    storageBucket: 'pharmgo-bd4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBBCDExaPXU0tauRsP1pQsY0YJfCxAPck',
    appId: '1:489498507185:ios:92890ca58ba1f678b66f90',
    messagingSenderId: '489498507185',
    projectId: 'pharmgo-bd4c6',
    storageBucket: 'pharmgo-bd4c6.appspot.com',
    iosBundleId: 'com.example.pharmgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBBCDExaPXU0tauRsP1pQsY0YJfCxAPck',
    appId: '1:489498507185:ios:2ded8e68e2d24b2cb66f90',
    messagingSenderId: '489498507185',
    projectId: 'pharmgo-bd4c6',
    storageBucket: 'pharmgo-bd4c6.appspot.com',
    iosBundleId: 'com.example.pharmgo.RunnerTests',
  );
}
